using System;
using System.Xml.Serialization;

namespace Noodle.Data.SqlPackage
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.17929
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02", IsNullable = false)]
    public partial class DeploymentReport
    {
        private string[] errorsField;

        private string[] warningsField;

        private DeploymentReportAlert[] alertsField;

        private DeploymentReportOperation[] operationsField;

        /// <remarks/>
        [XmlArrayItem("Error", IsNullable = false)]
        public string[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Warning", IsNullable = false)]
        public string[] Warnings
        {
            get
            {
                return this.warningsField;
            }
            set
            {
                this.warningsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Alert", IsNullable = false)]
        public DeploymentReportAlert[] Alerts
        {
            get
            {
                return this.alertsField;
            }
            set
            {
                this.alertsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Operation", IsNullable = false)]
        public DeploymentReportOperation[] Operations
        {
            get
            {
                return this.operationsField;
            }
            set
            {
                this.operationsField = value;
            }
        }

        public bool HasErrors
        {
            get
            {
                return Errors != null && Errors.Length > 0;
            }
        }

        public bool HasWarnings
        {
            get
            {
                return Warnings != null && Warnings.Length > 0;
            }
        }

        public bool HasAlerts
        {
            get
            {
                return Alerts != null && Alerts.Length > 0;
            }
        }

        public bool HasOperations
        {
            get
            {
                return Operations != null && Operations.Length > 0;
            }
        }

        public bool HasInfomation
        {
            get
            {
                return HasErrors || HasWarnings || HasErrors || HasOperations;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class DeploymentReportAlert
    {
        private IssueType[] issueField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Issue")]
        public IssueType[] Issue
        {
            get
            {
                return this.issueField;
            }
            set
            {
                this.issueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class IssueType
    {

        private string valueField;

        private int idField;

        /// <remarks/>
        [XmlAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class ItemType
    {

        private ItemTypeIssue[] issueField;

        private string valueField;

        private string typeField;

        /// <remarks/>
        [XmlElement("Issue")]
        public ItemTypeIssue[] Issue
        {
            get
            {
                return this.issueField;
            }
            set
            {
                this.issueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class ItemTypeIssue
    {

        private int idField;

        /// <remarks/>
        [XmlAttribute()]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [Serializable()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/sqlserver/dac/DeployReport/2012/02")]
    public partial class DeploymentReportOperation
    {

        private ItemType[] itemField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Item")]
        public ItemType[] Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
